### PR TITLE
Changes for OSX

### PR DESCRIPTION
**Pull request by pb-cdunn**
This builds in Travis and on my Mac. The latest blasr_libcpp compiles with Clang, so it makes sense to upgrade. However, it needed some changes too.

The test here doesn't pass because I haven't made the same changes to `src/test` yet. First, we need to work with the blasr_libcpp owners to simplify how that is built. I got it working with the changes in my repo:

* https://github.com/pb-cdunn/blasr_libcpp/tree/new

Anyway, this Pull-Request shows changes that I needed. In general, I prefer conditional includes to conditional defines. A conditional-include puts the if-statement in just one location, with a clear set of definitions, so it's easy to reason about.

I've also improved the README, so if you pull my changes you'll have that too.

### CODE REVIEW

**Comment by pbjd** [comment]
RE: work with blasr_libcpp owners, shouldn't be a problem.

**Comment by ylipacbio** [comment]
Oops, am I summoned?

**Comment by pb-cdunn** [comment]
@ylipacbio, Not yet. I like your refactoring. For the integration with pbdagcon, I'm working with Herb first to see how he wants the Makefiles to look. Then, I'll submit a PullRequest for blasr_libcpp and we can discuss there.

**Comment by pb-cdunn** [comment]
Replaced with #12.

**Pull request closed without merging**
